/**
 * Schema migrations: applied on boot, counted for `/api/v1/meta`.
 *
 * The files in `drizzle/` are generated by `npm run db:generate` and ship with the
 * image. Applying them at boot (rather than from a Job or by hand) keeps "the pod
 * that serves this schema" and "the migration that created it" in one artefact —
 * but two replicas starting together would race, so the whole step runs under a
 * Postgres advisory lock: the second boot waits, then finds nothing left to do.
 *
 * A failure here must kill the process (see `src/hooks.server.js`). With
 * `maxUnavailable: 0` the old pods keep serving and the rollout simply stalls,
 * which is the outcome you want at 2am.
 */

import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import { createDb } from './index.js';

/** Folder `drizzle-kit` writes to, resolved against the working directory. */
const MIGRATIONS_FOLDER = 'drizzle';

/**
 * Advisory lock id shared by every replica of this app.
 *
 * Arbitrary but fixed: advisory locks live in one global namespace per database, so
 * the value only has to be unlikely to collide with another application's. It is an
 * int4 on purpose — `pg_advisory_lock(bigint)` is the only single-argument overload,
 * so the value widens without an explicit cast.
 */
export const MIGRATION_LOCK_KEY = 411_500_215;

/** Drizzle's own bookkeeping, created by `migrate()` on first use. */
const MIGRATIONS_SCHEMA = 'drizzle';
const MIGRATIONS_TABLE = '__drizzle_migrations';

/**
 * Applies every pending migration, under the advisory lock.
 *
 * Uses its own single connection: `pg_advisory_lock` is session-scoped, so the lock
 * and the migrations have to travel over the same socket — a pooled handle could
 * hand the migration a different connection than the one holding the lock.
 *
 * @param {string} databaseUrl
 * @returns {Promise<void>} Resolves once the database is at the shipped version.
 */
export async function applyMigrations(databaseUrl) {
	const { client, db } = createDb(databaseUrl, { max: 1 });
	try {
		await client`select pg_advisory_lock(${MIGRATION_LOCK_KEY})`;
		try {
			await migrate(db, { migrationsFolder: path.resolve(MIGRATIONS_FOLDER) });
		} finally {
			// Releasing explicitly rather than leaning on the disconnect keeps a pooler
			// (pgbouncer in session mode, say) from holding the lock after we are done.
			await client`select pg_advisory_unlock(${MIGRATION_LOCK_KEY})`;
		}
	} finally {
		await client.end();
	}
}

/**
 * How many migrations this build ships — the `binarySchemaVersion` of
 * `/api/v1/meta`.
 *
 * Read from the journal rather than by counting `.sql` files: the journal is what
 * `migrate()` itself walks, so the two can never disagree about what will be
 * applied. `scripts/deploy.sh` counts `drizzle/NNNN_*.sql` instead, because it has
 * no app to ask — `migrations.test.js` holds the two definitions to the same
 * number so that gate cannot drift away from this one.
 *
 * @returns {Promise<number>}
 */
export async function countShippedMigrations() {
	const journalPath = path.resolve(MIGRATIONS_FOLDER, 'meta', '_journal.json');
	const journal = JSON.parse(await readFile(journalPath, 'utf8'));
	return Array.isArray(journal?.entries) ? journal.entries.length : 0;
}

/**
 * How many migrations the database has recorded — the `dbSchemaVersion` of
 * `/api/v1/meta`.
 *
 * A database that has never been migrated has no bookkeeping table yet; that is
 * version 0, not an error, so the caller can still report a reachable but empty
 * database.
 *
 * @param {import('postgres').Sql} client
 * @returns {Promise<number>}
 */
export async function countAppliedMigrations(client) {
	const [table] =
		await client`select to_regclass(${`${MIGRATIONS_SCHEMA}.${MIGRATIONS_TABLE}`}) as name`;
	if (!table?.name) return 0;

	const [row] = await client`
		select count(*)::int as count from ${client(MIGRATIONS_SCHEMA)}.${client(MIGRATIONS_TABLE)}
	`;
	return Number(row?.count ?? 0);
}
